### ISSUE TITLE
1.17 crash report. 

### ISSUE THREAD

**Issue by ShadoUrufu** [dexman545/Fabric-Passable-Leaves#6]
[crash-2021-06-18_17.08.48-server.txt](https://github.com/dexman545/Fabric-Passable-Leaves/files/6679147/crash-2021-06-18_17.08.48-server.txt)

May be due ot mods, but i'm guessing it's the new azelia leaves that were added.

**Comment by dexman545** [comment]
Fixed in 2.0.0
