### ISSUE TITLE
Vines and glow lichen are unable to be placed on leaves

### ISSUE THREAD

**Issue by somefoolouthere** [dexman545/Fabric-Passable-Leaves#7]
Leaves that are passable are unable to have vines placed on them. Due to this, it also causes jungle and swamp trees to generate floating vines.

**Comment by dexman545** [comment]
Fixed in 2.0.1

**Comment by EthanDSYT** [comment]
> Fixed in 2.0.1

Please, fix it in 1.16.5 versions
