### ISSUE TITLE
{request} Please make speed reduction for walking threw leave configurable.

### ISSUE THREAD

**Issue by KMFrench1** [dexman545/Fabric-Passable-Leaves#9]
Can you please make the speed reduction for leave configurable? I am having  very hard time ridding threw forest on my horse because I slow to a crawl every time my head touch's a leave block.
Thanks

**Comment by dexman545** [comment]
Added in 2.0.0
The values are finicky!

**Comment by KMFrench1** [comment]
Thanks so much for adding the config file. I am very grateful. I know you just rewrote the mod so it is ok if you don't want to, but would it be possible to have a 1.18.1 version too. My mod pack has so many mods that are still not updated to 1.18.2 yet, so I can't use the new version. More the half the pact is still 1.18.1. Agian feel free to ignore this if it is alot of work. I don't know anything about code so I have no idea how hard or easy this would be. Thanks agian.

**Comment by dexman545** [comment]
You can use https://fabricmc.net/wiki/tutorial:dependency_overrides to remove the version requirement, it may work out of the box.

**Comment by KMFrench1** [comment]
I just tried the override thing. It did not work. I may have done it wrong. anyway, here is the log if you want it. https://paste.ee/p/4GjVc

**Comment by KMFrench1** [comment]
Thanks so much. I am already messing with setting to find a balance I enjoy. Thanks agian
